import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/modules/Header";
import { Suggestions } from "../components/modules/Suggestions";
import { TicketList } from "../components/modules/TicketList";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <TicketList />
      <Suggestions />
    </div>
  );
};

export default Home;
